package com.mecon.desktop.service

import com.mecon.core.container.MeconBundleCodec
import java.nio.file.Files
import java.io.File
import java.util.Base64
import kotlinx.coroutines.runBlocking
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/** Contract fixture generated by web/packages/frozen-score's writeMeconArchive implementation. */
class BrowserMeconContractTest {
    @Test
    fun desktopReadsBrowserWrittenContainerAndUnknownModule() {
        val encoded = checkNotNull(
            javaClass.getResourceAsStream("/web/browser-written-mecon.base64"),
        ).bufferedReader().use { it.readText() }
        val file = Files.createTempFile("browser-written-", ".mecon").toFile()
        try {
            file.writeBytes(Base64.getMimeDecoder().decode(encoded))
            val rawEntries = MeconArchive.read(file)
            val document = MeconBundleCodec.readDocument(
                rawEntries.mapValues { (_, bytes) -> bytes.decodeToString() },
            )

            assertEquals("Web Contract", document.activeScore?.metadata?.title)
            assertEquals("future.module", document.modules.single().type)
            assertEquals(9, document.modules.single().schemaVersion)
            assertTrue("\"futureField\":\"preserved\"" in rawEntries.getValue("modules/future.json").decodeToString())
            assertEquals("future", document.manifest.workspace.activeModuleId)
        } finally {
            file.delete()
        }
    }

    @Test
    fun desktopReadsLatestPlaywrightExportWhenRequested() = runBlocking {
        val exportPath = System.getenv("MECON_BROWSER_EXPORT") ?: return@runBlocking
        val file = File(exportPath)
        assertTrue(file.isFile, "Playwright export does not exist: $exportPath")

        val document = MeconDocumentService().load(file)

        assertEquals("Web E2E", document.activeScore?.metadata?.title)
        assertEquals("Inactive", document.scores.single { it.id.value == "inactive-score" }.metadata.title)
        assertEquals("future.module", document.module("future")?.type)
        assertEquals(9, document.module("future")?.schemaVersion)
        assertTrue("\"futureField\":\"preserved\"" in document.module("future")?.payload.toString())
        assertEquals("future", document.manifest.workspace.activeModuleId)
    }
}
