package com.mecon.desktop.service

import java.io.File
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Desktop half of the browser-export compatibility gate generated by the F1 Playwright path.
 *
 * Only `:apps:desktop:freePracticeBrowserExportTest` runs this class, and that task always supplies
 * the archive path. A missing property therefore means the gate was invoked wrong, not that there is
 * nothing to check — reporting it as a pass is how "verified" silently stops meaning anything.
 */
class FreePracticeBrowserExportTest {
    @Test
    fun desktopReadsBrowserExportedFreePracticeModuleAndScore() = runBlocking {
        val path = requireNotNull(System.getProperty("freepractice.browser.export.path")) {
            "Run :apps:desktop:freePracticeBrowserExportTest (optionally with " +
                "-Pfreepractice.browser.export.path=...) after the web F1 E2E has written the archive"
        }
        val file = File(path)
        assertTrue(file.isFile, "Browser export does not exist: $file")

        val document = MeconDocumentService().load(file)
        val snapshot = assertNotNull(document.activeFreePracticeSnapshot())
        assertEquals(1, snapshot.document.workspace.idiomInstances.size)
        assertTrue(snapshot.document.workspace.slots.isNotEmpty())
        assertTrue(snapshot.score.voiceTracks.isNotEmpty())
        assertEquals(
            "Free writing sibling",
            document.scores.single { it.id.value == "free-practice-sibling" }.metadata.title,
        )
        val unknownModule = assertNotNull(document.module("future-practice"))
        assertEquals("future.practice", unknownModule.type)
        assertEquals(17, unknownModule.schemaVersion)
        assertTrue("free-practice-preserved" in unknownModule.payload.toString())
        assertEquals("free-practice", document.manifest.workspace.activeModuleId)
        val rawManifest = Json.parseToJsonElement(
            MeconArchive.read(file).getValue("manifest.json").decodeToString(),
        ).jsonObject
        val rawWorkspace = rawManifest.getValue("workspace").jsonObject
        assertEquals("free-practice", rawWorkspace.getValue("activeModuleId").jsonPrimitive.content)
        assertEquals(
            listOf(snapshot.score.id.value),
            rawWorkspace.getValue("selectedScoreIds").jsonArray.map { it.jsonPrimitive.content },
        )
    }
}
