package com.mecon.plugins.theory.desktop

import com.mecon.desktop.uikit.i18n.I18nRegistry
import com.mecon.desktop.uikit.i18n.Language

internal object TheoryAnalysisStrings {
    private val zh = mapOf(
        "plugin.theory.panel.title" to "乐理分析",
        "plugin.theory.panel.fixedVoice.distribution" to "声部分配",
        "plugin.theory.panel.fixedVoice.distribution.22" to "高2 / 低2",
        "plugin.theory.panel.fixedVoice.distribution.31" to "高3 / 低1",
        "plugin.theory.panel.fixedVoice.noScore" to "无乐谱",
        "plugin.theory.panel.fixedVoice.ready" to "可分析：%d 个固定声部",
        "plugin.theory.panel.fixedVoice.invalid" to "当前乐谱不能作为固定声部缩谱",
        "plugin.theory.panel.fixedVoice.moreDiagnostics" to "另有 %d 项",
        "plugin.theory.panel.fixedVoice.voiceMap" to "声部",
        "plugin.theory.panel.fixedVoice.staffVoice" to "谱表 %d · 声部 %d",
        "plugin.theory.panel.fixedVoice.selectionContext" to "选中音",
        "plugin.theory.panel.fixedVoice.noFixedSelection" to "未选中固定声部音符",
        "plugin.theory.panel.fixedVoice.selected" to "当前",
        "plugin.theory.panel.fixedVoice.previous" to "前一音",
        "plugin.theory.panel.fixedVoice.next" to "后一音",
        "plugin.theory.panel.fixedVoice.vertical" to "同时音",
        "plugin.theory.panel.fixedVoice.role.soprano" to "女高音",
        "plugin.theory.panel.fixedVoice.role.alto" to "女低音",
        "plugin.theory.panel.fixedVoice.role.tenor" to "男高音",
        "plugin.theory.panel.fixedVoice.role.bass" to "男低音",
        "plugin.theory.panel.fixedVoice.role.baritone" to "男中音",
        "plugin.theory.panel.fixedVoice.role.inner" to "内声部",
        "plugin.theory.panel.fixedVoice.role.outer" to "外声部",
        "plugin.theory.panel.fixedVoice.role.unspecified" to "未指定",
        "plugin.theory.panel.fixedVoice.error.needGrandStaff" to "需要至少两行谱表",
        "plugin.theory.panel.fixedVoice.error.staffMissing" to "谱表不存在",
        "plugin.theory.panel.fixedVoice.error.voiceCount" to "谱表声部数与当前分配不匹配",
        "plugin.theory.panel.fixedVoice.error.chord" to "固定声部中含和弦事件 %s",
        "plugin.theory.panel.rules.summary" to "规则",
        "plugin.theory.panel.rules.selection" to "关联规则",
        "plugin.theory.panel.rules.time" to "%s 的规则",
        "plugin.theory.panel.rules.unavailable" to "当前无法生成规则分析",
        "plugin.theory.panel.rules.empty" to "无关联规则",
        "plugin.theory.panel.rules.anchors" to "音符：%s",
        "plugin.theory.panel.rules.kind.hard" to "错误",
        "plugin.theory.panel.rules.kind.soft" to "警告",
        "plugin.theory.panel.rules.kind.hint" to "提示",
        "plugin.theory.panel.rules.kind.warning" to "提醒",
        "plugin.theory.panel.rules.kind.indication" to "标记",
        "plugin.theory.panel.rules.role.primary" to "主音符",
        "plugin.theory.panel.rules.role.related" to "相关",
        "plugin.theory.panel.rules.role.source" to "来源",
        "plugin.theory.panel.rules.role.target" to "目标",
        "plugin.theory.panel.rules.role.context" to "参照",
    )

    private val en = mapOf(
        "plugin.theory.panel.title" to "Theory Analysis",
        "plugin.theory.panel.fixedVoice.distribution" to "Voice Distribution",
        "plugin.theory.panel.fixedVoice.distribution.22" to "Upper 2 / Lower 2",
        "plugin.theory.panel.fixedVoice.distribution.31" to "Upper 3 / Lower 1",
        "plugin.theory.panel.fixedVoice.noScore" to "No score",
        "plugin.theory.panel.fixedVoice.ready" to "Ready: %d fixed voices",
        "plugin.theory.panel.fixedVoice.invalid" to "Current score is not a fixed-voice reduction",
        "plugin.theory.panel.fixedVoice.moreDiagnostics" to "%d more",
        "plugin.theory.panel.fixedVoice.voiceMap" to "Voices",
        "plugin.theory.panel.fixedVoice.staffVoice" to "Staff %d · Voice %d",
        "plugin.theory.panel.fixedVoice.selectionContext" to "Selected Note",
        "plugin.theory.panel.fixedVoice.noFixedSelection" to "No fixed-voice note selected",
        "plugin.theory.panel.fixedVoice.selected" to "Current",
        "plugin.theory.panel.fixedVoice.previous" to "Previous",
        "plugin.theory.panel.fixedVoice.next" to "Next",
        "plugin.theory.panel.fixedVoice.vertical" to "Vertical",
        "plugin.theory.panel.fixedVoice.role.soprano" to "Soprano",
        "plugin.theory.panel.fixedVoice.role.alto" to "Alto",
        "plugin.theory.panel.fixedVoice.role.tenor" to "Tenor",
        "plugin.theory.panel.fixedVoice.role.bass" to "Bass",
        "plugin.theory.panel.fixedVoice.role.baritone" to "Baritone",
        "plugin.theory.panel.fixedVoice.role.inner" to "Inner",
        "plugin.theory.panel.fixedVoice.role.outer" to "Outer",
        "plugin.theory.panel.fixedVoice.role.unspecified" to "Unspecified",
        "plugin.theory.panel.fixedVoice.error.needGrandStaff" to "At least two staves are required",
        "plugin.theory.panel.fixedVoice.error.staffMissing" to "Staff is missing",
        "plugin.theory.panel.fixedVoice.error.voiceCount" to "Staff voice count does not match this distribution",
        "plugin.theory.panel.fixedVoice.error.chord" to "Chord event %s appears in a fixed voice",
        "plugin.theory.panel.rules.summary" to "Rules",
        "plugin.theory.panel.rules.selection" to "Related Rules",
        "plugin.theory.panel.rules.time" to "Rules at %s",
        "plugin.theory.panel.rules.unavailable" to "Rule analysis is unavailable",
        "plugin.theory.panel.rules.empty" to "No related rules",
        "plugin.theory.panel.rules.anchors" to "Notes: %s",
        "plugin.theory.panel.rules.kind.hard" to "Error",
        "plugin.theory.panel.rules.kind.soft" to "Warning",
        "plugin.theory.panel.rules.kind.hint" to "Hint",
        "plugin.theory.panel.rules.kind.warning" to "Notice",
        "plugin.theory.panel.rules.kind.indication" to "Mark",
        "plugin.theory.panel.rules.role.primary" to "Primary",
        "plugin.theory.panel.rules.role.related" to "Related",
        "plugin.theory.panel.rules.role.source" to "Source",
        "plugin.theory.panel.rules.role.target" to "Target",
        "plugin.theory.panel.rules.role.context" to "Context",
    )

    fun install() {
        I18nRegistry.register(Language.CHINESE, zh)
        I18nRegistry.register(Language.ENGLISH, en)
    }
}
