package com.mecon.renderer.render

import com.mecon.api.computed.ComputedScore
import com.mecon.renderer.elements.ArticulationElement
import com.mecon.renderer.elements.BeamGroupElement
import com.mecon.renderer.elements.ElementRenderContext
import com.mecon.renderer.elements.SlurElement
import com.mecon.renderer.elements.StaffAttachmentElement
import com.mecon.renderer.elements.TieElement
import com.mecon.renderer.elements.TupletElement
import com.mecon.renderer.geometry.RelativePoint
import com.mecon.renderer.geometry.StaffSpace
import com.mecon.renderer.layout.RenderLayoutConfig
import com.mecon.renderer.layout.StaffLayoutInfo
import com.mecon.renderer.layout.SystemLayout
import com.mecon.renderer.layout.UnifiedLayoutResult
import com.mecon.renderer.render.spatial.ScoreSpatialAdapter
import com.mecon.renderer.smufl.BravuraFont

/** Performs the full, ordered render pass for a [UnifiedLayoutResult]. */
context(BravuraFont)
internal class FullScoreRenderer(
    private val config: RenderLayoutConfig,
    private val transformer: CoordinateTransformer,
    private val structuralElementRenderer: StructuralElementRenderer,
    private val notationElementPassRenderer: NotationElementPassRenderer,
    private val beamGroupProcessor: BeamGroupProcessor,
    private val tieLayoutComputer: TieLayoutComputer,
    private val slurLayoutComputer: SlurLayoutComputer,
    private val articulationLayoutComputer: ArticulationLayoutComputer,
    private val tupletLayoutComputer: TupletLayoutComputer,
    private val annotationStaffRenderer: AnnotationStaffRenderer,
    private val lineStartHeaderRenderer: LineStartHeaderRenderer,
    private val titleBlockRenderer: TitleBlockRenderer,
    private val postLayoutMarkerRenderer: PostLayoutMarkerRenderer,
) {
    /**
     * Produce [RichElement]s for the given [layoutResult].
     *
     * @param measureRange When non-null, spanner computers scan only this measure window.
     * @param systemFilter When non-null, only elements belonging to these system indices are emitted.
     *   The effective measure range for spanner filtering is derived automatically from [systemFilter]
     *   when [measureRange] is null. Useful for per-page / per-system streaming (Phase 3) and for
     *   the [com.mecon.renderer.render.RenderEngine.renderRange] API.
     *   The title block (anchored to page 1) is included only when [systemFilter] is null or contains
     *   system index 0.
     */
    fun render(
        layoutResult: UnifiedLayoutResult,
        computedScore: ComputedScore,
        pluginComponents: List<com.mecon.renderer.plugin.PluginRenderComponent>,
        measureRange: IntRange? = null,
        systemFilter: Set<Int>? = null,
        /**
         * When non-null, element IDs are generated by this function instead of the local counter.
         * Pass a shared generator when rendering multiple system subsets that will be merged into one
         * [RenderResult] (e.g. the streaming path in [com.mecon.renderer.render.RenderEngine.renderStreaming]),
         * so every element across all pages has a globally unique ID.
         */
        idGenerator: (() -> RenderElementId)? = null,
    ): List<RichElement> {
        // Derive the effective measure filter: explicit range takes precedence; otherwise union of the
        // filtered systems' measure ranges (so spanner computers scan only the relevant window).
        val effectiveMeasureFilter: IntRange? = when {
            measureRange != null -> measureRange
            systemFilter != null -> {
                var lo = Int.MAX_VALUE; var hi = Int.MIN_VALUE
                for (sys in layoutResult.systems) {
                    if (sys.systemIndex in systemFilter) {
                        if (sys.measureRange.first < lo) lo = sys.measureRange.first
                        if (sys.measureRange.last > hi) hi = sys.measureRange.last
                    }
                }
                if (lo <= hi) lo..hi else null
            }
            else -> null
        }
        val sysFilter: (SystemLayout) -> Boolean =
            if (systemFilter != null) ({ it.systemIndex in systemFilter }) else ({ true })

        var elementIdCounter = 0
        fun nextId() = idGenerator?.invoke() ?: RenderElementId.global(elementIdCounter++.toLong())

        val barlines = layoutResult.barlineLayouts.all()
        val measureBoundaries = ScoreSpatialAdapter.computeMeasureBoundaries(barlines, layoutResult.width)
        val systemStartX = barlines.firstOrNull()?.x ?: config.firstSystemIndent
        val collector = RenderElementCollector(measureBoundaries, systemStartX)

        val staffLayoutByIndex = layoutResult.staffLayouts.associateBy { it.staffIndex }
        val systemByIndex = layoutResult.systems.associateBy { it.systemIndex }
        val systemIndexByMeasure = HashMap<Int, Int>()
        for (system in layoutResult.systems) {
            for (measure in system.measureRange) systemIndexByMeasure[measure] = system.systemIndex
        }
        // No flat-stack fallback: a staff absent from its (known) system collapsed out (fully hidden),
        // so its glyphs must be skipped, not drawn at the global Y. staffForSystem already falls back for
        // unknown systems.
        fun staffFor(systemIndex: Int, staffIndex: Int): StaffLayoutInfo? =
            layoutResult.staffForSystem(systemIndex, staffIndex)

        val layoutQuery = LayoutQuery(layoutResult, staffLayoutByIndex, computedScore)

        collector.addElements(structuralElementRenderer.renderStaffLineElements(layoutResult, ::nextId, sysFilter))
        collector.addElements(structuralElementRenderer.renderHeaderBracketsAndLabels(layoutResult, ::nextId, sysFilter))

        notationElementPassRenderer.renderTimeSlotElements(
            layoutResult, computedScore, systemByIndex, ::staffFor, ::nextId, collector::collect,
            slotFilter = if (systemFilter != null) ({ it.systemIndex in systemFilter }) else ({ true }),
        )

        for (system in layoutResult.systems) {
            if (!sysFilter(system)) continue
            val onlyThis = { s: SystemLayout -> s.systemIndex == system.systemIndex }
            structuralElementRenderer.renderSystemStructuralLines(
                layoutResult, computedScore, ::nextId, onlyThis
            ).forEach(collector::collectRich)
            lineStartHeaderRenderer.render(layoutResult, computedScore, ::staffFor, ::nextId, collector::collect, onlyThis)
        }

        val beamProcessingResult = beamGroupProcessor.processBeamGroups(
            layoutResult, staffLayoutByIndex, measureFilter = effectiveMeasureFilter,
            geometry = computedScore.runtime.geometry?.beams ?: emptyMap(),
        )
        val dummyCtx = ElementRenderContext(
            offset = RelativePoint.ZERO,
            transformer = transformer,
            idGenerator = ::nextId,
            computedScore = computedScore
        )

        notationElementPassRenderer.renderStemFlagElements(
            layoutResult, beamProcessingResult, ::staffFor, dummyCtx, collector::collect,
            voiceFilter = if (effectiveMeasureFilter != null) ({ it.measureNumber in effectiveMeasureFilter }) else ({ true }),
        )

        for (groupData in beamProcessingResult.beamGroupRenderData) {
            if (effectiveMeasureFilter != null && groupData.measureNumber != -1 &&
                groupData.measureNumber !in effectiveMeasureFilter) continue
            val beamGroupElement = BeamGroupElement(
                notes = groupData.beamNoteInfos,
                stemDirection = groupData.stemDirection,
                beamThickness = config.engravingDefaults.beamThickness * groupData.noteScale.value,
                beamSpacing = config.engravingDefaults.beamSpacing * groupData.noteScale.value,
                stemThickness = config.engravingDefaults.stemThickness * groupData.noteScale.value,
            )
            collector.collect(beamGroupElement.render(dummyCtx), groupData.staffIndex,
                systemIndexByMeasure[groupData.measureNumber] ?: 0)
        }

        val geometry = computedScore.runtime.geometry
        val articulationLayouts = articulationLayoutComputer.computeArticulationLayouts(
            computedScore, layoutQuery, geometry, measureFilter = effectiveMeasureFilter
        )
        for (articulationLayout in articulationLayouts.values) {
            val articulationElement = ArticulationElement(articulationLayout)
            collector.collect(articulationElement.render(dummyCtx), articulationLayout.staffIndex,
                systemIndexByMeasure[articulationLayout.measureNumber] ?: 0)
        }

        val tieLayouts = tieLayoutComputer.computeTieLayouts(
            computedScore,
            layoutQuery,
            measureFilter = effectiveMeasureFilter,
            geometry = geometry,
        )
        for (tieLayout in tieLayouts) {
            val tieElement = TieElement(tieLayout, config)
            collector.collect(tieElement.render(dummyCtx), tieLayout.staffIndex,
                systemIndexByMeasure[tieLayout.measureNumber] ?: 0)
        }

        val slurLayouts = slurLayoutComputer.computeSlurLayouts(
            computedScore,
            layoutQuery,
            articulationLayouts,
            stemAdjustments = beamProcessingResult.stemAdjustments,
            beamGroups = beamProcessingResult.beamGroupRenderData,
            geometry = geometry,
            measureFilter = effectiveMeasureFilter,
        )
        for (slurLayout in slurLayouts) {
            if (systemFilter != null && slurLayout.systemIndex !in systemFilter) continue
            val slurElement = SlurElement(slurLayout, config)
            collector.collect(slurElement.render(dummyCtx), slurLayout.staffIndex,
                slurLayout.systemIndex)
        }

        val tupletLayouts = tupletLayoutComputer.computeTupletLayouts(
            computedScore, layoutQuery,
            stemAdjustments = beamProcessingResult.stemAdjustments,
            measureFilter = effectiveMeasureFilter,
            geometry = geometry,
        )
        for (tupletLayout in tupletLayouts) {
            val tupletElement = TupletElement(tupletLayout, config)
            collector.collect(tupletElement.render(dummyCtx), tupletLayout.staffIndex,
                systemIndexByMeasure[tupletLayout.measureNumber] ?: 0)
        }

        for (placed in layoutResult.placedAttachments) {
            if (systemFilter != null && placed.systemIndex !in systemFilter) continue
            val staffLayout = staffFor(placed.systemIndex, placed.staffIndex) ?: continue
            val ctx = ElementRenderContext(
                offset = RelativePoint(StaffSpace.ZERO, staffLayout.centerY),
                transformer = transformer,
                idGenerator = ::nextId,
                computedScore = computedScore
            )
            collector.collect(StaffAttachmentElement(placed).render(ctx), placed.staffIndex, placed.systemIndex)
        }

        collector.addElements(annotationStaffRenderer.render(layoutResult, idGenerator = ::nextId,
            predicate = if (systemFilter != null) ({ it.systemIndex in systemFilter }) else null))
        // Title block is page-anchored (above system 0); include it only when rendering the first system.
        if (systemFilter == null || 0 in systemFilter) {
            layoutResult.titleBlock?.let { block ->
                collector.addElements(titleBlockRenderer.render(block, ::nextId))
            }
        }

        if (pluginComponents.isNotEmpty()) {
            val pluginCtx = com.mecon.renderer.plugin.PluginRenderContext(
                transformer = transformer,
                computedScore = computedScore,
                layoutResult = layoutResult,
                idGenerator = ::nextId
            )
            for (plugin in pluginComponents) {
                collector.addElements(plugin.render(pluginCtx))
            }
        }

        // Post-layout overlays are deliberately last: they overlay completed engraving and never
        // participate in proportional spacing, vertical extents, line breaking, or pagination.
        postLayoutMarkerRenderer.render(
            layoutResult,
            ::nextId,
            systemFilter,
            showMeasureNumbers = computedScore.runtime.viewPreferences.showMeasureNumbers,
        ).forEach(collector::collectRich)
        return collector.toRichElements()
    }
}
