package com.mecon.features.freepractice

/** Chinese chord-detail copy shared verbatim by the desktop and Web projections. */
object PracticeChordDetailStrings {
    private val values = mapOf(
        "exploration.chordDetail.unavailableTitle" to "和弦详情",
        "exploration.chordDetail.unavailable" to "该章节尚未提供详细解释。",
        "exploration.chordDetail.partial" to "部分解释尚缺章节详情。",
        "exploration.chordDetail.routes" to "构造线路",
        "exploration.chordDetail.routeHint" to "选择线路以查看完整功能、倾向与谱例",
        "exploration.chordDetail.sources" to "来源",
        "exploration.chordDetail.apply" to "应用此解释",
        "exploration.chordDetail.chooseRoute" to "请先选择线路",
        "exploration.chordDetail.structure" to "结构",
        "exploration.chordDetail.function" to "功能",
        "exploration.chordDetail.functionSubstitution" to "功能替代",
        "exploration.chordDetail.construction" to "构造",
        "exploration.chordDetail.substitution.dominant" to "替代属和弦功能。",
        "exploration.chordDetail.substitution.secondaryDominant" to "替代指向第 {degree} 级的副属和弦功能。",
        "exploration.chordDetail.substitution.predominant" to "替代属前和弦功能。",
        "exploration.chordDetail.construction.omittedFromFormula" to "{basis}{symbol} ({formula}) 省略根音 ({root})",
        "exploration.chordDetail.construction.structuralCaption" to "结构示意；不表示转位或四部排列。灰色音为省略音。",
        "exploration.chordDetail.construction.modalScale" to "以{degree}级为临时主音的{mode}{path}音级",
        "exploration.chordDetail.construction.modalScale.ascending" to "上行",
        "exploration.chordDetail.construction.modalScale.descending" to "下行",
        "exploration.chordDetail.construction.modalScale.caption" to "七个音级均用全音符表示；黑色音为所选和弦音，灰色音为其余调式音级。",
        "exploration.chordDetail.construction.minorSubdominant" to "从{source}自然小调借入；灰色为当前大调的{reference}",
        "exploration.chordDetail.construction.minorSubdominant.tonicReference" to "主和弦",
        "exploration.chordDetail.construction.minorSubdominant.dominantReference" to "属和弦",
        "exploration.chordDetail.construction.minorSubdominant.caption" to "构造示意；两个和弦不表示和弦进行。灰色为当前大调的{reference}，正常颜色为所选借入和弦。",
        "exploration.chordDetail.mode.ionian" to "伊奥尼亚",
        "exploration.chordDetail.mode.dorian" to "多利亚",
        "exploration.chordDetail.mode.phrygian" to "弗里几亚",
        "exploration.chordDetail.mode.lydian" to "利底亚",
        "exploration.chordDetail.mode.mixolydian" to "混合利底亚",
        "exploration.chordDetail.mode.aeolian" to "艾奥利亚",
        "exploration.chordDetail.mode.locrian" to "洛克里亚",
        "exploration.chordDetail.dominantNinth.primaryName" to "属九和弦",
        "exploration.chordDetail.dominantNinth.secondaryName" to "{degree}级副属九和弦",
        "exploration.chordDetail.dominantSeventh.primaryName" to "属七和弦",
        "exploration.chordDetail.dominantSeventh.secondaryName" to "{degree}级副属七和弦",
        "exploration.chordDetail.degree.1" to "一",
        "exploration.chordDetail.degree.2" to "二",
        "exploration.chordDetail.degree.3" to "三",
        "exploration.chordDetail.degree.4" to "四",
        "exploration.chordDetail.degree.5" to "五",
        "exploration.chordDetail.degree.6" to "六",
        "exploration.chordDetail.degree.7" to "七",
        "exploration.chordDetail.route.primaryBadge" to "本调",
        "exploration.chordDetail.route.secondaryBadge" to "副属",
        "exploration.chordDetail.route.primarySubtitle" to "当前调性的属功能解释",
        "exploration.chordDetail.route.secondarySubtitle" to "临时指向{degree}级的属功能解释",
        "exploration.chordDetail.tendency" to "倾向音",
        "exploration.chordDetail.operation.alter" to "变化和弦成员",
        "exploration.chordDetail.operation.add" to "加入和弦成员",
        "exploration.chordDetail.operation.omit" to "省略隐含根音",
        "exploration.chordDetail.operation.stack" to "三度叠置",
        "exploration.chordDetail.operation.respell" to "等音重拼",
        "exploration.chordDetail.operation.legacy" to "旧构造轨迹",
        "exploration.chordDetail.source.primary" to "原著依据",
        "exploration.chordDetail.source.inference" to "项目推论",
        "exploration.chordDetail.source.recommendation" to "产品建议",
        "exploration.chordDetail.diminished.name" to "减七和弦",
        "exploration.chordDetail.diminished.summary" to "省略根音属降九和弦，可有多条功能构造线路。",
        "exploration.chordDetail.diminished.stackedMinorThirds" to "四个和弦音以小三度等分八度。",
        "exploration.chordDetail.diminished.threeSoundingClasses" to "十二平均律中共有三个可听音响类别。",
        "exploration.chordDetail.diminished.rootlessFlatNinth" to "省略根音的属降九",
        "exploration.chordDetail.diminished.dominantFunction" to "在所选临时调性领域中承担属功能。",
        "exploration.chordDetail.diminished.lowerToOmittedRoot" to "指定成员下行半音，显露省略的属根音。",
        "exploration.chordDetail.diminished.localLeadingTone" to "局部导音上行到临时主音。",
        "exploration.chordDetail.diminished.omittedDominantRoot" to "属根音被隐含并省略。",
        "exploration.chordDetail.neapolitan.name" to "拿坡里和弦",
        "exploration.chordDetail.neapolitan.summary" to "从小下属关系引入的降二级大三和弦。",
        "exploration.chordDetail.neapolitan.minorSubdominantOrigin" to "源自同主音小调的小下属关系。",
        "exploration.chordDetail.neapolitan.predominantFunction" to "承担属前功能，通常导向终止四六或属和弦。",
        "exploration.chordDetail.neapolitan.minorModeSupertonic" to "小调领域的降二级大三和弦",
        "exploration.chordDetail.secondaryHarmony.secondaryDominantName" to "副属和弦",
        "exploration.chordDetail.secondaryHarmony.secondaryLeadingName" to "副导和弦",
        "exploration.chordDetail.secondaryHarmony.modalAugmentedName" to "调式增三和弦",
        "exploration.chordDetail.secondaryHarmony.modalColorName" to "中古调式色彩和弦",
        "exploration.chordDetail.secondaryHarmony.summary" to "由对应中古调式的音级与上行或下行变化构造。",
        "exploration.chordDetail.secondaryHarmony.modalTag" to "中古调式派生",
        "exploration.chordDetail.secondaryHarmony.modalDerivation" to "完整调式音级中对应的三度叠置音构成所选和弦。",
        "exploration.chordDetail.secondaryHarmony.secondaryDominantFunction" to "临时指向目标音级的属功能。",
        "exploration.chordDetail.secondaryHarmony.secondaryLeadingFunction" to "临时指向目标音级的导音功能。",
        "exploration.chordDetail.secondaryHarmony.colorFunction" to "保留其中古调式来源的色彩功能。",
        "exploration.chordDetail.secondaryHarmony.modalRoute" to "中古调式音级构造",
        "exploration.chordDetail.augmentedSixth.italianName" to "意大利增六和弦",
        "exploration.chordDetail.augmentedSixth.germanName" to "德国增六和弦",
        "exploration.chordDetail.augmentedSixth.frenchName" to "法国增六和弦",
        "exploration.chordDetail.augmentedSixth.half_diminishedName" to "半减七增六和弦",
        "exploration.chordDetail.augmentedSixth.summary" to "以增六拼写连接较远和弦，两端变化音汇聚到共同目标音。",
        "exploration.chordDetail.augmentedSixth.vagrantTag" to "游移和弦",
        "exploration.chordDetail.augmentedSixth.spelling" to "保留增六音程拼写，不与等音属七解释合并。",
        "exploration.chordDetail.augmentedSixth.function" to "作为对应副属功能的属前和弦指向所选目标音级。",
        "exploration.chordDetail.augmentedSixth.flatNeighbor" to "降方邻音下行半音到目标音。",
        "exploration.chordDetail.augmentedSixth.sharpNeighbor" to "升方邻音上行半音到目标音。",
        "exploration.chordDetail.augmentedSixth.italianFormula" to "重属七省根后的意大利增六构造",
        "exploration.chordDetail.augmentedSixth.germanFormula" to "重属降九省根后的德国增六构造",
        "exploration.chordDetail.augmentedSixth.frenchFormula" to "ii7 两个和弦音半音变化后的法国增六构造",
        "exploration.chordDetail.augmentedSixth.half_diminishedFormula" to "将半减七的大二度外音重释为增六两端",
        "exploration.chordDetail.construction.augmentedSixth.rootlessProcess" to
            "{basis}{basisSymbol} ({basisFormula}) 省略根音 ({root})，得到{intermediateName} ({intermediateFormula})；{alteration}，得到 {resultSymbol} ({resultFormula})",
        "exploration.chordDetail.construction.augmentedSixth.namedProcess" to
            "{originSymbol} ({originFormula})；{alteration}，得到 {resultSymbol} ({resultFormula})",
        "exploration.chordDetail.construction.augmentedSixth" to
            "{kind}：{descending} 与 {ascending} 构成增六，并共同解决到 {resolution}",
        "exploration.chordDetail.construction.augmentedSixth.caption" to "构造来源 → 增六和弦 → 两端同时解决到目标音",
        "exploration.chordDetail.construction.augmentedSixth.italian" to "意大利增六",
        "exploration.chordDetail.construction.augmentedSixth.german" to "德国增六",
        "exploration.chordDetail.construction.augmentedSixth.french" to "法国增六",
        "exploration.chordDetail.construction.augmentedSixth.half_diminished" to "半减七增六",
        "exploration.chordDetail.construction.augmentedSixth.diminishedTriad" to "减三和弦",
        "exploration.chordDetail.construction.augmentedSixth.diminishedSeventh" to "减七和弦",
        "exploration.chordDetail.construction.augmentedSixth.alteration.italian" to "三音再下行半音",
        "exploration.chordDetail.construction.augmentedSixth.alteration.german" to "三音再下行半音",
        "exploration.chordDetail.construction.augmentedSixth.alteration.french" to "三音上行半音、五音下行半音",
        "exploration.chordDetail.construction.augmentedSixth.alteration.half_diminished" to "将根音与七音的大二度重释为增六",
        "exploration.chordDetail.minorSubdominant.name" to "小下属关系和弦",
        "exploration.chordDetail.minorSubdominant.summary" to "从同主音或下属音自然小调借入当前大调。",
        "exploration.chordDetail.minorSubdominant.borrowedTag" to "借用和弦",
        "exploration.chordDetail.minorSubdominant.predominantTag" to "属前功能",
        "exploration.chordDetail.minorSubdominant.origin" to "属于同主音自然小调、下属音自然小调，或同时属于两者。",
        "exploration.chordDetail.minorSubdominant.function" to "具体功能由所选借入和弦在当前调中的音级决定。",
        "exploration.chordDetail.minorSubdominant.borrowingRoute" to "小下属关系借入",
        "exploration.symmetric" to "对称",
        "exploration.vagrant" to "游移和弦",
        "exploration.diatonic" to "调内",
        "exploration.chordDetail.diatonic.name" to "调内三和弦",
        "exploration.chordDetail.diatonic.summary" to "由当前音阶三度叠置构成。",
        "exploration.chordDetail.diatonic.tertian" to "取交替音级构成。",
        "exploration.chordDetail.diatonic.scaleDegree" to "音级构造",
    )

    fun text(key: String): String = values[key] ?: key
}

