/** SMuFL code points used by score-editor controls. Keep PUA values named and centralized. */
export const SMUFL_GLYPHS = Object.freeze({
  noteWhole: "\uE1D2",
  noteHalfUp: "\uE1D3",
  noteQuarterUp: "\uE1D5",
  noteEighthUp: "\uE1D7",
  note16thUp: "\uE1D9",
  note32ndUp: "\uE1DB",
  note64thUp: "\uE1DD",
  note128thUp: "\uE1DF",
  noteDoubleWhole: "\uE1D0",
  restWhole: "\uE4E3",
  restHalf: "\uE4E4",
  restQuarter: "\uE4E5",
  restEighth: "\uE4E6",
  rest16th: "\uE4E7",
  rest32nd: "\uE4E8",
  rest64th: "\uE4E9",
  rest128th: "\uE4EA",
  augmentationDot: "\uE1E7",
  accidentalFlat: "\uE260",
  accidentalNatural: "\uE261",
  accidentalSharp: "\uE262",
  accidentalDoubleSharp: "\uE263",
  accidentalDoubleFlat: "\uE264",
  graceAcciaccatura: "\uE560",
  graceAppoggiatura: "\uE562",
  articAccent: "\uE4A0",
  articStaccato: "\uE4A2",
  articTenuto: "\uE4A4",
  articStaccatissimo: "\uE4A6",
  articMarcato: "\uE4AC",
});

export const DURATION_GLYPHS = Object.freeze([
  Object.freeze({ value: "WHOLE", label: "全音符", note: SMUFL_GLYPHS.noteWhole, rest: SMUFL_GLYPHS.restWhole }),
  Object.freeze({ value: "HALF", label: "二分音符", note: SMUFL_GLYPHS.noteHalfUp, rest: SMUFL_GLYPHS.restHalf }),
  Object.freeze({ value: "QUARTER", label: "四分音符", note: SMUFL_GLYPHS.noteQuarterUp, rest: SMUFL_GLYPHS.restQuarter }),
  Object.freeze({ value: "EIGHTH", label: "八分音符", note: SMUFL_GLYPHS.noteEighthUp, rest: SMUFL_GLYPHS.restEighth }),
  Object.freeze({ value: "SIXTEENTH", label: "十六分音符", note: SMUFL_GLYPHS.note16thUp, rest: SMUFL_GLYPHS.rest16th }),
  Object.freeze({ value: "THIRTY_SECOND", label: "三十二分音符", note: SMUFL_GLYPHS.note32ndUp, rest: SMUFL_GLYPHS.rest32nd }),
]);
